version: '3'

networks:
  proxy:
    external:
      name: docker-compose_proxy


services:
  sushidiet-check:
     build: ../Sushidiet/Webapps/check.sushidiet/
     container_name: sushidiet-check-nginx
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: check.${SUSHIDIET_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: check.${SUSHIDIET_DOMAIN}
       LETSENCRYPT_EMAIL: ${SUSHIDIET_EMAIL}

  sushidiet-recette:
     build: ../Sushidiet/Webapps/recette.sushidiet/
     container_name: sushidiet-recette-nginx
     restart: always
     tty: true
     stdin_open: true
     expose:
      - 5000
     networks:
       - proxy
     environment:
       VIRTUAL_HOST: recette.${SUSHIDIET_DOMAIN}
       VIRTUAL_PORT: 5000
       LETSENCRYPT_HOST: recette.${SUSHIDIET_DOMAIN}
       LETSENCRYPT_EMAIL: ${SUSHIDIET_EMAIL}
